title: Nelson Blog
email: xiezhongxi0525@foxmail.com
author:
  picture: https://avatars2.githubusercontent.com/u/8802276?v=3&s=460 #URL FORMAT
  name: Nelson
  location: 广州 - 中国
  description: “奔3程序员正在实现梦想!”  
description: 奔3程序员正在实现梦想!
baseurl: "/"
url: https://github.com/XieXieZhongxi/XieXieZhongxi.github.io
twitter_username: hugocolombo23
github_username:  XieXieZhongxi
github_url: https://github.com/XieXieZhongxi/XieXieZhongxi.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
