title: 仲习的主页
escription: > # this means to ignore newlines until "baseurl:"
  Born as G(r)eek.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiezhongxi.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "ThodorisBais"

# Author Settings
author: 谢仲习
author-img: zhongxi.jpg
about-author: iOS开发工程师,现居广州
# twitter: ThodorisBais
# facebook: toubou.techblog
github: XieXieZhongxi
# linkedin: thodorisbais
# tumblr: thodoris.bais@gmail.com
email: xiezhongxi0525@foxmail.com

# Disqus
discus-identifier: thodorisbais # add your discus identifier

# Tracker
analytics: UA-108110726-1

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
