title: Nelson Den
email: xiezhongxi0525@foxmail.com
author:
  picture: https://avatars2.githubusercontent.com/u/8802276?v=3&s=460 #URL FORMAT
  name: Nelson
  location: 广州 - 中国
  description: “iOS开发工程师,现居广州”  
description: iOS开发工程师,现居广州
baseurl: "/"
url: https://github.com/XieXieZhongxi/XieXieZhongxi.github.io
#twitter_username: hugocolombo23
github_username:  XieXieZhongxi
github_url: https://XieXieZhongxi.github.io/XieXieZhongxi.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
